### ISSUE TITLE
数据集的疑问

### ISSUE THREAD

**Issue by fengyuchao97** [Event-AHU/FELT_SOT_Benchmark#4]
您好，我在运行代码的时候发现，No such file or directory 关于 FELT/train/list.txt ...train.txt ...test.txt等，我想问一下里面内容是啥呀，我尝试了文件夹名称，但这显然不对，能否麻烦您提供一下

**Comment by captainlong9** [comment]
> 您好，我在运行代码的时候发现，No such file or directory 关于 FELT/train/list.txt ...train.txt ...test.txt等，我想问一下里面内容是啥呀，我尝试了文件夹名称，但这显然不对，能否麻烦您提供一下

相关的文件已经上传到了./data文件夹中
